# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eviction',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eviction',
            name='lon',
            field=models.FloatField(),
        ),
    ]
