# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20160918_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eviction',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eviction',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
