# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20160923_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='eviction',
            name='category',
            field=models.CharField(choices=[('EVC', 'Eviction'), ('SEC', 'Security Deposits'), ('REP', 'Repairs'), ('OTH', 'Other')], default='EVC', max_length=3),
            preserve_default=False,
        ),
    ]
