# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='children',
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='start', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
