# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='advocates',
        ),
    ]
