# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20160927_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='children',
            field=models.CharField(default='damage deposits, repairs, illegal rent increase, illegal landlord entry into unit, evictions', max_length=100),
            preserve_default=False,
        ),
    ]
