# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_question_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='children',
        ),
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contest.Question'),
        ),
    ]
