# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20160930_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_text',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
