# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20161022_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='leaf',
        ),
        migrations.RemoveField(
            model_name='question',
            name='parent',
        ),
        migrations.AddField(
            model_name='choice',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chi', to='contest.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='leaf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs', to='contest.Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='tooltip',
            field=models.CharField(max_length=500),
        ),
    ]
