# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20161022_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='cform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('laddress', models.CharField(max_length=100)),
                ('lcity', models.CharField(max_length=100)),
                ('lpostal', models.CharField(max_length=100)),
                ('deposittotal', models.IntegerField()),
                ('faddress', models.CharField(max_length=100)),
                ('fcity', models.CharField(max_length=100)),
                ('fprovince', models.CharField(max_length=100)),
                ('fpostal', models.CharField(max_length=100)),
                ('evictreason', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='tooltip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
